=== Miguee048/ifcd0210/MF0491_3CLIENTE/UF1841/E2/dtd cb canarias.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<!ELEMENT pivots ((jugador+))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT jugadores ((bases, escoltas, aleros, ala_pivots, pivots))>
<!ELEMENT jugador ((nombre, dorsal))>
<!ELEMENT escoltas ((jugador+))>
<!ELEMENT equipo ((jugadores, cuerpo_tecnico))>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT dorsal (#PCDATA)>
<!ELEMENT cuerpo_tecnico ((entrenador, ayudantes_entrenador))>
<!ELEMENT cbcanarias ((equipo))>
<!ELEMENT bases ((jugador+))>
<!ELEMENT ayudantes_entrenador ((nombre+))>
<!ELEMENT aleros ((jugador+))>
<!ELEMENT ala_pivots ((jugador+))>

=== Miguee048/ifcd0210/MF0491_3CLIENTE/UF1841/E2/xml cb canarias xmlspy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<!DOCTYPE cbcanarias SYSTEM "C:\Users\luism\Desktop\ACIVIDADE2\dtd cb canarias.dtd">
<cbcanarias>
	<equipo>
		<jugadores>
			<bases>
				<jugador>
					<nombre>Rodrigo San Miguel</nombre>
					<dorsal>00</dorsal>
				</jugador>
				<jugador>
					<nombre>Ferran Basas</nombre>
					<dorsal>10</dorsal>
				</jugador>
				<jugador>
					<nombre>Davin White</nombre>
					<dorsal>34</dorsal>
				</jugador>
			</bases>
			<escoltas>
				<jugador>
					<nombre>Nico Richotti</nombre>
					<dorsal>5</dorsal>
				</jugador>
				<jugador>
					<nombre>Thad Macfadden</nombre>
					<dorsal>12</dorsal>
				</jugador>
				<jugador>
					<nombre>Luca_Staiger</nombre>
					<dorsal>01</dorsal>
				</jugador>
			</escoltas>
			<aleros>
				<jugador>
					<nombre>Javier_Beiran</nombre>
					<dorsal>33</dorsal>
				</jugador>
				<jugador>
					<nombre>Nico Brusino</nombre>
					<dorsal>09</dorsal>
				</jugador>
			</aleros>
			<ala_pivots>
				<jugador>
					<nombre>Tim Abromaitis</nombre>
					<dorsal>21</dorsal>
				</jugador>
				<jugador>
					<nombre>Gillet</nombre>
					<dorsal>31</dorsal>
				</jugador>
				<jugador>
					<nombre>Tomasz Gielo</nombre>
					<dorsal>06</dorsal>
				</jugador>
			</ala_pivots>
			<pivots>
				<jugador>
					<nombre>Colton Iverson</nombre>
					<dorsal>04</dorsal>
				</jugador>
				<jugador>
					<nombre>Sebas Saiz</nombre>
					<dorsal>11</dorsal>
				</jugador>
				<jugador>
					<nombre>Petit Niang</nombre>
					<dorsal>07</dorsal>
				</jugador>
			</pivots>
		</jugadores>
		<cuerpo_tecnico>
			<entrenador>Txus Vidorreta</entrenador>
			<ayudantes_entrenador>
				<nombre>Marco Justo</nombre>
				<nombre>Nacho Ya√±ez</nombre>
			</ayudantes_entrenador>
		</cuerpo_tecnico>
	</equipo>
</cbcanarias>
